# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

pip install huggingface_hub

import os, torch
from datasets import load_dataset, concatenate_datasets
from transformers import (AutoTokenizer, AutoModelForSeq2SeqLM, Seq2SeqTrainer, Seq2SeqTrainingArguments,default_data_collator)

os.environ["TOKENIZERS_PARALLELISM"] = "false"

device = "cuda" if torch.cuda.is_available() else "cpu"
print("Device in use:", device)
dataset_list =[]
medque = load_dataset("lavita/MedQuAD", split="train")
dataset_list.append(medque)
pubmedq = load_dataset("pubmed_qa","pqa_labeled", split="train")
dataset_list.append(pubmedq)
magic = load_dataset("lavita/ChatDoctor-HealthCareMagic-100k", split="train")
dataset_list.append(magic)

def standardise_the_data_set(ex):
    instru, res = None, None

    if "question" in ex and "answer" in ex:
        instru = ex["question"]
        res = ex["answer"]
    elif "question" in ex and "final_decision" in ex:
        instru = ex["question"]
        res = ex["final_decision"]
    elif "instruction" in ex and "output" in ex:
        instru = ex["instruction"]
        res = ex["output"]
    return {
        "instruction": str(instru) if instru else None,
        "response": str(res) if res else None
    }

com_dataset = concatenate_datasets(dataset_list)
com_dataset = com_dataset.map(standardise_the_data_set)
com_dataset = com_dataset.filter(
    lambda x: (
        isinstance(x.get("instruction"), str) and x["instruction"].strip() != "" and
        isinstance(x.get("response"), str) and x["response"].strip() != ""
    )
)
seen=set()
def _rem_dup(ex):
  if ex["instruction"] in seen:
    return False
  seen.add(ex["instruction"])
  return True
com_dataset = com_dataset.filter(_rem_dup)

com_dataset = com_dataset.shuffle(seed=42)
max_examples = min(8000, len(com_dataset))
combined_dataset = com_dataset.select(range(max_examples))

max_input = 256
max_target = 128
model_name = "MBZUAI/LaMini-Flan-T5-783M"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSeq2SeqLM.from_pretrained(model_name)
model.gradient_checkpointing_enable()
def training(ex):
  input = [str(x) for x in ex['instruction']]
  target = [str(x) for x in ex['response']]
  model_input = tokenizer(input, max_length=max_input, truncation=True, padding="max_length")
  model_label = tokenizer(target, max_length=max_target, truncation=True, padding="max_length")
  model_input["labels"] = model_label["input_ids"]
  return model_input
tokenized_dataset = com_dataset.map(training, batched=True)
tokenized_dataset.set_format(type="torch")
tokenized_dataset = tokenized_dataset.train_test_split(test_size=0.2, seed=42)

training_args = Seq2SeqTrainingArguments(output_dir="./tinyllama-ft", per_device_train_batch_size=1,
gradient_accumulation_steps=8,
learning_rate=3e-5,
num_train_epochs=2,
max_grad_norm=1.0, fp16=False,
bf16=False, logging_steps=500,
eval_strategy="steps")
trainer = Seq2SeqTrainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_dataset["train"],
    eval_dataset=tokenized_dataset["test"],
    processing_class=tokenizer,
)

trainer.train()

